//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer
    {
        public Dealer()
        {
            this.Commission = new HashSet<Commission>();
        }
    
        public int DealerId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Commission> Commission { get; set; }
    }
}
